import Head from 'next/head'
//import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { auth, provider } from "../utils/firebase"
import { signInWithPopup, User } from "firebase/auth"
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const [user, setUser] = useState<User | null>(null)

  function handleSignout() {
    setUser(null);
  }

  const handleClick =()=>{
      signInWithPopup(auth,provider).then((data)=>{
        console.log('user data', data)
        setUser(data.user)
      })
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="referrer" content="no-referrer" />
      </Head>
      <main className={styles.main}>
        
        { user ?
          <div>
            <button onClick={() => handleSignout()}>Sign out</button>
            <br/>
            <img src={user?.photoURL ? user.photoURL: ''} alt="user pic"></img>
            <h3>{user?.displayName}</h3>
          </div>
          :
          <button onClick={handleClick}>Signin With Google</button>
        }
      </main>
    </>
  )
}
